### ISSUE TITLE
Dockerfile zufügen

### ISSUE THREAD

**Issue by Merovius** [nnev/website#11]
Wir wollen ein Dockerfile, welches alle Teile der Webseite (i.e. den jekyll-gebauten Teil, die Datenbank, c14h, yarpnarp und das termine tool) in einen container packt, damit Änderungen einfacher lokal und auf travis testbar sind.

**Comment by stapelberg** [comment]
Für Docker auf Travis ist ggf. http://michael.stapelberg.de/Artikel/docker-on-travis-for-new-tools-and-fast-runs interessant.
