### ISSUE TITLE
Add helper-scripts for development

### ISSUE THREAD

**Issue by cherti** [nnev/website#72]
Having the commands in the [README](https://github.com/nnev/website/blob/master/README.md) in one or multiple script(s) might make development more comfortable as one does not have to pull the lengthy docker-commands from readme or shell history.

**Comment by joker234** [comment]
@cherti isn't this solved by b3e113365bf6b91a2bb167356e1f2968152a7ea7?

**Comment by cherti** [comment]
it is.
