### ISSUE TITLE
Website-container doesn't build

### ISSUE THREAD

**Issue by cherti** [nnev/website#81]
When starting the website container via `docker run --name=nnev-website --net=host -p 127.0.0.1:80:80 -v $PWD:/usr/src/ nnev-website` as described in our documentation, the build crashes during assembling of the container with

```
Dependency Error: Yikes! It looks like you don't have redcarpet or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- redcarpet.so' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting 'anfahrt.md':
                    redcarpet
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    redcarpet
```

@koebi maybe the solution is obvious? Otherwise someone has do dig into it.

**Comment by sur5r** [comment]
ruby-redcarpet in Debian testing is currently only built against ruby 2.3.0 while default ruby is 2.5.0.This is due to the fact Backporting ruby-redcarpet from sid results in a package being compiled against 2.5.0.

**Comment by cherti** [comment]
@sur5r any blockers keeping ruby-redcarped in sid or does the issue resolve itself if we just wait 2 weeks or so?

**Comment by joker234** [comment]
I didn't look dig into that issue, but is there a reason why are not using `bundle install` and a `Gemfile` for dependencies? Is this because of the compatibility with the setup on the deployment server?

**Comment by joker234** [comment]
P.S.: is there a reason why we are not using travis wtih this repository?

**Comment by sur5r** [comment]
There was one FTBFS bug which has been resolved. So ideally, this should resolve itself in 1 or 2 days.

**Comment by sur5r** [comment]
ruby-redcarpet 3.4.0-4 (built against 2.3.0 AND 2.5.0) has migrated to testing. Please retry, should work now.

**Comment by cherti** [comment]
@sur5r yep, looks good, closing.

@joker234 because no one ever spent the time to set it up. If you think it's desirable, open an issue for it and highlight me there, I'll add it to the to-be-created hackathon-milestone later
