### ISSUE TITLE
c14h: new talks don't trigger website-rebuild

### ISSUE THREAD

**Issue by koebi** [nnev/website#83]
I tried to announce a new talk via the website for "2018-03-29" and made sure to have the date right. The website didn't trigger a rebuild, though :(

**Comment by chrko** [comment]
Not yet verified: The path of `update-website` has changed from `/usr/bin` to `/usr/local/bin`. This update is missing in the systemd service files of c14h and yarpnarp. :/

**Comment by sur5r** [comment]
Fixed.
