### ISSUE TITLE
Don't use default ports for Docker

### ISSUE THREAD

**Issue by joker234** [nnev/website#95]
using default ports is a very bad idea for systems with not only nnev infrastructure and totally useless for debugging purposes, because the docker containers would use production environments. Please change them to non-default ports.

**Comment by cherti** [comment]
What do you mean by default ports here?

**Comment by joker234** [comment]
Default ports are for example 5432 for Postgres and 80 for http. See also `grep "^\(http\|postgresql\)" /etc/services`.

In my case I sometimes have a running postgresql for debugging and running services unrelated from nnev on my computer, so the docker setup would fail.

**Comment by sur5r** [comment]
Half-OT/Nitpick: `getent services http postgres`

**Comment by joker234** [comment]
> Half-OT/Nitpick: `getent services http postgres`

thx, searched but forgot about that :smiley:
